In [1]:
import numpy as np


In [3]:


# ================= SECTION A =================

# 1. Create NumPy array from 1 to 20
print("\nQ1: Create NumPy array from 1 to 20")
arr = np.arange(1, 21)
print(arr)

# 2. Create array of 5 decimal values
print("\nQ2: Create array of 5 decimal values")
dec = np.array([1.2, 2.5, 3.7, 4.1, 5.9])
print(dec)

# 3. 3x3 array filled with ones
print("\nQ3: Create 3x3 array filled with ones")
ones = np.ones((3,3))
print(ones)

# 4. 3x3 array filled with zeros
print("\nQ4: Create 3x3 array filled with zeros")
zeros = np.zeros((3,3))
print(zeros)



# ================= SECTION B =================

arr2 = np.array([[1,2,3],[4,5,6]])

# 5. Shape
print("\nQ5: Find the shape of the array")
print(arr2.shape)

# 6. Dimensions
print("\nQ6: Find the number of dimensions")
print(arr2.ndim)

# 7. Total elements
print("\nQ7: Find total number of elements")
print(arr2.size)



# ================= SECTION C =================

# 8. First and last element
print("\nQ8: Print first and last element")
print("First:", arr[0])
print("Last:", arr[-1])

# 9. First 3 elements
print("\nQ9: Print first three elements")
print(arr[:3])

# 10. Middle element of 3x3 matrix
print("\nQ10: Find middle element of 3x3 matrix")
matrix = np.arange(1,10).reshape(3,3)
print(matrix)
print("Middle element:", matrix[1,1])

# 11. Second row
print("\nQ11: Print second row of matrix")
print(matrix[1])



# ================= SECTION D =================

a = np.array([1,2,3])
b = np.array([4,5,6])

# 12. Add arrays
print("\nQ12: Add two arrays")
print(a + b)

# 13. Subtract arrays
print("\nQ13: Subtract two arrays")
print(b - a)

# 14. Multiply each element by 5
print("\nQ14: Multiply each element by 5")
print(a * 5)

# 15. Square each element
print("\nQ15: Square each element")
print(a ** 2)



# ================= SECTION E =================

# 16. Sum
print("\nQ16: Find sum of elements")
print(np.sum(arr))

# 17. Mean
print("\nQ17: Find mean of elements")
print(np.mean(arr))

# 18. Max and Min
print("\nQ18: Find maximum and minimum")
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))



# ================= SECTION F =================

# 19. Values > 10
print("\nQ19: Print values greater than 10")
print(arr[arr > 10])

# 20. Replace values < 5 with 0
print("\nQ20: Replace values less than 5 with 0")
arr_modified = arr.copy()
arr_modified[arr_modified < 5] = 0
print(arr_modified)






Q1: Create NumPy array from 1 to 20
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Q2: Create array of 5 decimal values
[1.2 2.5 3.7 4.1 5.9]

Q3: Create 3x3 array filled with ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Q4: Create 3x3 array filled with zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Q5: Find the shape of the array
(2, 3)

Q6: Find the number of dimensions
2

Q7: Find total number of elements
6

Q8: Print first and last element
First: 1
Last: 20

Q9: Print first three elements
[1 2 3]

Q10: Find middle element of 3x3 matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Middle element: 5

Q11: Print second row of matrix
[4 5 6]

Q12: Add two arrays
[5 7 9]

Q13: Subtract two arrays
[3 3 3]

Q14: Multiply each element by 5
[ 5 10 15]

Q15: Square each element
[1 4 9]

Q16: Find sum of elements
210

Q17: Find mean of elements
10.5

Q18: Find maximum and minimum
Maximum: 20
Minimum: 1

Q19: Print values greater than 10
[11 12 13 14 15 16 17 18 19 20]

Q20: Replace values less tha